name: Generate Image Lists

on:
  push:
    paths:
      - 'src/assets/img/ai-art-exhibition/**'
      - 'src/assets/img/lerobot-hackathon/**'
      - 'generate-image-lists.py'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-lists:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Generate image lists
      run: python generate-image-lists.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/assets/img/ai-art-exhibition/images.json
        git add src/assets/img/lerobot-hackathon/images.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update image lists"
        git push
